name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker buildx create --use
        docker build -t tinmistry/tempcicd:latest .
      env:
        DOCKER_CLI_AGGREGATE: 1

    - name: Log in to Docker Hub
      run: |
        docker login -u "tinumistry" -p "@123" 
        docker push tinmistry/tempcicd:latest

      
